[general]

import = [
	"./theme.toml"
]

live_config_reload = true

[window]
padding = { x = 5, y = 5 }

[font]
# "Fira code" font with for everything
# Note that i HATE italic fonts, so no italic
normal = { family = "Fira Code", style = "Medium" }
italic = { family = "Fira Code", style = "Medium" }
bold = { family = "Fira Code", style = "Bold" }
bold_italic = { family = "Fira Code", style = "Bold" }

[cursor]
style = { shape = "Beam", blinking = "off"}

[keyboard]
bindings = [{ mods = "Alt", key = "V", action = "ToggleViMode"},]
